In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import os

project_path = "/content/drive/MyDrive/Signature_Project"

os.makedirs(project_path, exist_ok=True)

print("Project folder ready")

Project folder ready

In [ ]:
!ls "/content/drive/MyDrive/Signature_Project"

archive.zip

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
!ls "/content/drive/MyDrive/Signature_Project"

archive.zip

In [ ]:
!unzip "/content/drive/MyDrive/Signature_Project/archive.zip" -d "/content/drive/MyDrive/Signature_Project/cedar"

Archive:  /content/drive/MyDrive/Signature_Project/archive.zip
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/Readme.txt
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/Thumbs.db
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_10_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_11_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_12_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_13_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_14_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_15_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_16_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_12.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_13.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_14.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_15.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_16.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_17.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_18.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_19.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_2.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_20.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_21.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_22.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_23.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_24.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_3.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_4.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_5.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_6.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_7.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_8.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_17_9.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_18_1.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_18_10.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_18_11.png
  inflating: /content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg/forgeries_18_12.png

In [ ]:
!ls "/content/drive/MyDrive/Signature_Project/cedar"

signatures

In [ ]:
!ls "/content/drive/MyDrive/Signature_Project/cedar/signatures"

full_forg  full_org  Readme.txt

In [ ]:
import os

ORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"
FORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg"

org_count = len([f for f in os.listdir(ORG_PATH) if f.endswith(".png")])
forg_count = len([f for f in os.listdir(FORG_PATH) if f.endswith(".png")])

print("Original:", org_count)
print("Forgery :", forg_count)

Original: 1320
Forgery : 1320

In [ ]:
import os

PROCESSED_ORG = "/content/drive/MyDrive/Signature_Project/processed/full_org"
PROCESSED_FORG = "/content/drive/MyDrive/Signature_Project/processed/full_forg"

os.makedirs(PROCESSED_ORG, exist_ok=True)
os.makedirs(PROCESSED_FORG, exist_ok=True)

print("Processed folders created")

Processed folders created

In [ ]:
import cv2

img = cv2.imread(
    "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org/original_10_1.png"
)

gray = cv2.cvtColor(
    img,
    cv2.COLOR_BGR2GRAY
)

resized = cv2.resize(
    gray,
    (224,224)
)

cv2.imwrite(
    "/content/drive/MyDrive/Signature_Project/processed/full_org/test.png",
    resized
)

print("Done")

Done

In [ ]:
import cv2

img = cv2.imread(
    "/content/drive/MyDrive/Signature_Project/processed/full_org/test.png",
    0
)

print(img.shape)

(224, 224)

In [ ]:
import os
import cv2

ORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"
FORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg"

PROCESSED_ORG = "/content/drive/MyDrive/Signature_Project/processed/full_org"
PROCESSED_FORG = "/content/drive/MyDrive/Signature_Project/processed/full_forg"

folders = [
    (ORG_PATH, PROCESSED_ORG),
    (FORG_PATH, PROCESSED_FORG)
]

for input_folder, output_folder in folders:

    files = [f for f in os.listdir(input_folder)
             if f.endswith(".png")]

    for file in files:

        img_path = os.path.join(input_folder, file)

        img = cv2.imread(img_path)

        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

        resized = cv2.resize(gray, (224,224))

        save_path = os.path.join(output_folder, file)

        cv2.imwrite(save_path, resized)

    print("Finished:", output_folder)

print("Preprocessing Completed")

Finished: /content/drive/MyDrive/Signature_Project/processed/full_org
Finished: /content/drive/MyDrive/Signature_Project/processed/full_forg
Preprocessing Completed

In [ ]:
import os

print("Processed Original:",
      len(os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_org")))

print("Processed Forgery:",
      len(os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_forg")))

Processed Original: 1321
Processed Forgery: 1320

In [ ]:
import os

thumb_path = "/content/drive/MyDrive/Signature_Project/processed/full_org/Thumbs.db"

if os.path.exists(thumb_path):
    os.remove(thumb_path)

print("Thumbs.db removed")

Thumbs.db removed

In [ ]:
import os

print("Processed Original:",
      len([f for f in os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_org")
           if f.endswith(".png")]))

print("Processed Forgery:",
      len([f for f in os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_forg")
           if f.endswith(".png")]))

Processed Original: 1321
Processed Forgery: 1320

In [ ]:
import os

files = os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_org")

for f in files:
    if not f.endswith(".png"):
        print(f)

In [ ]:
import os

files = os.listdir("/content/drive/MyDrive/Signature_Project/processed/full_org")

print("test.png" in files)

True

In [ ]:
import os

os.remove(
    "/content/drive/MyDrive/Signature_Project/processed/full_org/test.png"
)

print("test.png removed")

test.png removed

In [ ]:
import os

print(
    len([
        f for f in os.listdir(
            "/content/drive/MyDrive/Signature_Project/processed/full_org"
        )
        if f.endswith(".png")
    ])
)

1320

In [ ]:
import os

files = sorted(os.listdir(
    "/content/drive/MyDrive/Signature_Project/processed/full_org"
))

for file in files[:10]:
    print(file)

original_10_1.png
original_10_10.png
original_10_11.png
original_10_12.png
original_10_13.png
original_10_14.png
original_10_15.png
original_10_16.png
original_10_17.png
original_10_18.png

In [ ]:
import os

files = sorted(os.listdir(
    "/content/drive/MyDrive/Signature_Project/processed/full_forg"
))

for file in files[:10]:
    print(file)

forgeries_10_1.png
forgeries_10_10.png
forgeries_10_11.png
forgeries_10_12.png
forgeries_10_13.png
forgeries_10_14.png
forgeries_10_15.png
forgeries_10_16.png
forgeries_10_17.png
forgeries_10_18.png

In [ ]:
positive_pairs = []

for i in range(1,6):

    img1 = f"original_10_{i}.png"
    img2 = f"original_10_{i+1}.png"

    positive_pairs.append(
        [img1, img2, 1]
    )

positive_pairs

[['original_10_1.png', 'original_10_2.png', 1],
 ['original_10_2.png', 'original_10_3.png', 1],
 ['original_10_3.png', 'original_10_4.png', 1],
 ['original_10_4.png', 'original_10_5.png', 1],
 ['original_10_5.png', 'original_10_6.png', 1]]

In [ ]:
negative_pairs = []

for i in range(1,6):

    img1 = f"original_10_{i}.png"
    img2 = f"forgeries_10_{i}.png"

    negative_pairs.append(
        [img1, img2, 0]
    )

negative_pairs

[['original_10_1.png', 'forgeries_10_1.png', 0],
 ['original_10_2.png', 'forgeries_10_2.png', 0],
 ['original_10_3.png', 'forgeries_10_3.png', 0],
 ['original_10_4.png', 'forgeries_10_4.png', 0],
 ['original_10_5.png', 'forgeries_10_5.png', 0]]

In [ ]:
import pandas as pd

pairs = []

for person in range(1, 56):

    for i in range(1, 24):

        img1 = f"original_{person}_{i}.png"
        img2 = f"original_{person}_{i+1}.png"

        pairs.append([img1, img2, 1])

print("Positive pairs:", len(pairs))
pairs[:5]

Positive pairs: 1265

[['original_1_1.png', 'original_1_2.png', 1],
 ['original_1_2.png', 'original_1_3.png', 1],
 ['original_1_3.png', 'original_1_4.png', 1],
 ['original_1_4.png', 'original_1_5.png', 1],
 ['original_1_5.png', 'original_1_6.png', 1]]

In [ ]:
negative_pairs = []

for person in range(1, 56):

    for i in range(1, 25):

        img1 = f"original_{person}_{i}.png"
        img2 = f"forgeries_{person}_{i}.png"

        negative_pairs.append([img1, img2, 0])

print("Negative pairs:", len(negative_pairs))
negative_pairs[:5]

Negative pairs: 1320

[['original_1_1.png', 'forgeries_1_1.png', 0],
 ['original_1_2.png', 'forgeries_1_2.png', 0],
 ['original_1_3.png', 'forgeries_1_3.png', 0],
 ['original_1_4.png', 'forgeries_1_4.png', 0],
 ['original_1_5.png', 'forgeries_1_5.png', 0]]

In [ ]:
import pandas as pd

all_pairs = pairs + negative_pairs

df = pd.DataFrame(
    all_pairs,
    columns=["image1", "image2", "label"]
)

print(df.shape)

df.head()

(2585, 3)

             image1            image2  label
0  original_1_1.png  original_1_2.png      1
1  original_1_2.png  original_1_3.png      1
2  original_1_3.png  original_1_4.png      1
3  original_1_4.png  original_1_5.png      1
4  original_1_5.png  original_1_6.png      1

In [ ]:
df.to_csv(
    "/content/drive/MyDrive/Signature_Project/pairs.csv",
    index=False
)

print("pairs.csv saved")

pairs.csv saved

In [ ]:
df.head(10)

              image1             image2  label
0   original_1_1.png   original_1_2.png      1
1   original_1_2.png   original_1_3.png      1
2   original_1_3.png   original_1_4.png      1
3   original_1_4.png   original_1_5.png      1
4   original_1_5.png   original_1_6.png      1
5   original_1_6.png   original_1_7.png      1
6   original_1_7.png   original_1_8.png      1
7   original_1_8.png   original_1_9.png      1
8   original_1_9.png  original_1_10.png      1
9  original_1_10.png  original_1_11.png      1

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Signature_Project/pairs.csv"
)

print(df.shape)

df.head()

(2585, 3)

             image1            image2  label
0  original_1_1.png  original_1_2.png      1
1  original_1_2.png  original_1_3.png      1
2  original_1_3.png  original_1_4.png      1
3  original_1_4.png  original_1_5.png      1
4  original_1_5.png  original_1_6.png      1

In [ ]:
import tensorflow as tf

print(tf.__version__)

2.20.0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Signature_Project/pairs.csv"
)

print(df.shape)

(2585, 3)

In [ ]:
import os

def get_image_path(filename):

    if filename.startswith("original"):
        return os.path.join(
            "/content/drive/MyDrive/Signature_Project/processed/full_org",
            filename
        )

    else:
        return os.path.join(
            "/content/drive/MyDrive/Signature_Project/processed/full_forg",
            filename
        )

In [ ]:
print(get_image_path("original_1_1.png"))

print(get_image_path("forgeries_1_1.png"))

/content/drive/MyDrive/Signature_Project/processed/full_org/original_1_1.png
/content/drive/MyDrive/Signature_Project/processed/full_forg/forgeries_1_1.png

In [ ]:
import cv2

row = df.iloc[0]

img1_path = get_image_path(row["image1"])
img2_path = get_image_path(row["image2"])

img1 = cv2.imread(img1_path, 0)
img2 = cv2.imread(img2_path, 0)

print("Image 1:", img1.shape)
print("Image 2:", img2.shape)
print("Label:", row["label"])

Image 1: (224, 224)
Image 2: (224, 224)
Label: 1

In [ ]:
print(img1)

[[241 242 237 ... 244 245 247]
 [241 240 244 ... 229 243 242]
 [241 241 241 ... 238 245 244]
 ...
 [238 238 237 ... 247 244 243]
 [238 238 238 ... 243 246 244]
 [237 240 244 ... 244 246 245]]

In [ ]:
img1 = img1 / 255.0

print(img1)

[[0.94509804 0.94901961 0.92941176 ... 0.95686275 0.96078431 0.96862745]
 [0.94509804 0.94117647 0.95686275 ... 0.89803922 0.95294118 0.94901961]
 [0.94509804 0.94509804 0.94509804 ... 0.93333333 0.96078431 0.95686275]
 ...
 [0.93333333 0.93333333 0.92941176 ... 0.96862745 0.95686275 0.95294118]
 [0.93333333 0.93333333 0.93333333 ... 0.95294118 0.96470588 0.95686275]
 [0.92941176 0.94117647 0.95686275 ... 0.95686275 0.96470588 0.96078431]]

In [ ]:
import numpy as np

X1 = []
X2 = []
y = []

print("Lists created")

Lists created

In [ ]:
for index, row in df.head(10).iterrows():

    print(row["image1"])
    print(row["image2"])
    print(row["label"])
    print("------")

original_1_1.png
original_1_2.png
1
------
original_1_2.png
original_1_3.png
1
------
original_1_3.png
original_1_4.png
1
------
original_1_4.png
original_1_5.png
1
------
original_1_5.png
original_1_6.png
1
------
original_1_6.png
original_1_7.png
1
------
original_1_7.png
original_1_8.png
1
------
original_1_8.png
original_1_9.png
1
------
original_1_9.png
original_1_10.png
1
------
original_1_10.png
original_1_11.png
1
------

In [ ]:
import cv2
import pandas as pd
import os

def get_image_path(filename):
    if filename.startswith("original"):
        return os.path.join(
            "/content/drive/MyDrive/Signature_Project/processed/full_org",
            filename
        )
    else:
        return os.path.join(
            "/content/drive/MyDrive/Signature_Project/processed/full_forg",
            filename
        )

df = pd.read_csv(
    "/content/drive/MyDrive/Signature_Project/pairs.csv"
)

X1 = []
X2 = []
y = []

for index, row in df.head(10).iterrows():
    img1_path = get_image_path(row["image1"])
    img2_path = get_image_path(row["image2"])

    img1 = cv2.imread(img1_path, 0) / 255.0
    img2 = cv2.imread(img2_path, 0) / 255.0

    X1.append(img1)
    X2.append(img2)
    y.append(row["label"])

print("Loaded:", len(X1), "pairs")

Loaded: 10 pairs

In [ ]:
print(len(X1))
print(len(X2))
print(len(y))

10
10
10

In [ ]:
X1[0].shape
y[0]

1

In [ ]:
print(len(X1))
print(len(X2))
print(len(y))

print(X1[0].shape)
print(X2[0].shape)

print(y[0])

10
10
10
(224, 224)
(224, 224)
1

In [ ]:
import numpy as np
X1 = np.array(X1)
X2 = np.array(X2)
y  = np.array(y)

In [ ]:
import numpy as np

X1 = np.array(X1)
X2 = np.array(X2)
y = np.array(y)

print(X1.shape)
print(X2.shape)
print(y.shape)

(10, 224, 224)
(10, 224, 224)
(10,)

In [ ]:
X1 = []
X2 = []
y = []

In [ ]:
import cv2

for _, row in df.iterrows():

    img1_path = get_image_path(row["image1"])
    img2_path = get_image_path(row["image2"])

    img1 = cv2.imread(img1_path, 0) / 255.0
    img2 = cv2.imread(img2_path, 0) / 255.0

    X1.append(img1)
    X2.append(img2)
    y.append(row["label"])

print("All pairs loaded")

All pairs loaded

In [ ]:
import numpy as np

X1 = np.array(X1)
X2 = np.array(X2)
y = np.array(y)

print(X1.shape)
print(X2.shape)
print(y.shape)

(2585, 224, 224)
(2585, 224, 224)
(2585,)

In [ ]:
X1 = X1.reshape(-1, 224, 224, 1)
X2 = X2.reshape(-1, 224, 224, 1)

print(X1.shape)
print(X2.shape)

(2585, 224, 224, 1)
(2585, 224, 224, 1)

In [ ]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, X2_train, X2_test, y_train, y_test = train_test_split(
    X1,
    X2,
    y,
    test_size=0.2,
    random_state=42
)

print("X1_train:", X1_train.shape)
print("X1_test :", X1_test.shape)

print("X2_train:", X2_train.shape)
print("X2_test :", X2_test.shape)

print("y_train :", y_train.shape)
print("y_test  :", y_test.shape)

X1_train: (2068, 224, 224, 1)
X1_test : (517, 224, 224, 1)
X2_train: (2068, 224, 224, 1)
X2_test : (517, 224, 224, 1)
y_train : (2068,)
y_test  : (517,)

In [ ]:
from tensorflow.keras.layers import (
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense,
    Input
)

from tensorflow.keras.models import Model

In [ ]:
input_layer = Input(shape=(224,224,1))

print(input_layer)

<KerasTensor shape=(None, 224, 224, 1), dtype=float32, sparse=False, ragged=False, name=keras_tensor>

In [ ]:
from tensorflow.keras.layers import Conv2D

conv_layer = Conv2D(
    filters=32,
    kernel_size=(3,3),
    activation="relu"
)

print(conv_layer)

<Conv2D name=conv2d, built=False>

In [ ]:
x = Conv2D(
    filters=32,
    kernel_size=(3,3),
    activation="relu"
)(input_layer)

print(x)

<KerasTensor shape=(None, 222, 222, 32), dtype=float32, sparse=False, ragged=False, name=keras_tensor_1>

In [6]:
import pandas as pd

df = pd.read_csv(
    "/content/drive/MyDrive/Signature_Project/pairs.csv"
)

print(df.shape)
df.head()

(2585, 3)

             image1            image2  label
0  original_1_1.png  original_1_2.png      1
1  original_1_2.png  original_1_3.png      1
2  original_1_3.png  original_1_4.png      1
3  original_1_4.png  original_1_5.png      1
4  original_1_5.png  original_1_6.png      1

In [7]:
import os
import cv2
import numpy as np
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Signature_Project/pairs.csv")

ORG_DIR = "/content/drive/MyDrive/Signature_Project/processed/full_org"
FORG_DIR = "/content/drive/MyDrive/Signature_Project/processed/full_forg"

def get_image_path(filename):
    if filename.startswith("original"):
        return os.path.join(ORG_DIR, filename)
    else:
        return os.path.join(FORG_DIR, filename)

X1 = []
X2 = []
y = []

for _, row in df.iterrows():

    img1 = cv2.imread(get_image_path(row["image1"]), 0) / 255.0
    img2 = cv2.imread(get_image_path(row["image2"]), 0) / 255.0

    X1.append(img1)
    X2.append(img2)
    y.append(row["label"])

X1 = np.array(X1)
X2 = np.array(X2)
y = np.array(y)

X1 = X1.reshape(-1,224,224,1)
X2 = X2.reshape(-1,224,224,1)

print(X1.shape)
print(X2.shape)
print(y.shape)

(2585, 224, 224, 1)
(2585, 224, 224, 1)
(2585,)

In [8]:
from sklearn.model_selection import train_test_split

X1_train, X1_test, X2_train, X2_test, y_train, y_test = train_test_split(
    X1,
    X2,
    y,
    test_size=0.2,
    random_state=42
)

print(X1_train.shape)
print(X1_test.shape)

(2068, 224, 224, 1)
(517, 224, 224, 1)

In [9]:
from tensorflow.keras.layers import (
    Input,
    Conv2D,
    MaxPooling2D,
    Flatten,
    Dense
)
from tensorflow.keras.models import Model

input_layer = Input(shape=(224,224,1))

x = Conv2D(
    filters=32,
    kernel_size=(3,3),
    activation="relu"
)(input_layer)

x = MaxPooling2D(pool_size=(2,2))(x)

x = Conv2D(
    filters=64,
    kernel_size=(3,3),
    activation="relu"
)(x)

x = MaxPooling2D(pool_size=(2,2))(x)

x = Flatten()(x)

x = Dense(128, activation="relu")(x)

embedding_network = Model(
    inputs=input_layer,
    outputs=x
)

embedding_network.summary()

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)        │ (None, 224, 224, 1)    │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_1 (Conv2D)               │ (None, 222, 222, 32)   │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d (MaxPooling2D)    │ (None, 111, 111, 32)   │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2d_2 (Conv2D)               │ (None, 109, 109, 64)   │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling2d_1 (MaxPooling2D)  │ (None, 54, 54, 64)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 186624)         │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 128)            │    23,888,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 23,906,816 (91.20 MB)

 Trainable params: 23,906,816 (91.20 MB)

 Non-trainable params: 0 (0.00 B)

In [10]:
input_a = Input(shape=(224,224,1))
input_b = Input(shape=(224,224,1))

embedding_a = embedding_network(input_a)
embedding_b = embedding_network(input_b)

print(embedding_a)
print(embedding_b)

<KerasTensor shape=(None, 128), dtype=float32, sparse=False, ragged=False, name=keras_tensor_9>
<KerasTensor shape=(None, 128), dtype=float32, sparse=False, ragged=False, name=keras_tensor_10>

In [11]:
from tensorflow.keras.layers import Lambda
import tensorflow as tf

distance = Lambda(
    lambda tensors: tf.abs(tensors[0] - tensors[1])
)([embedding_a, embedding_b])

print(distance)

<KerasTensor shape=(None, 128), dtype=float32, sparse=False, ragged=False, name=keras_tensor_14>

In [12]:
prediction = Dense(
    1,
    activation="sigmoid"
)(distance)

print(prediction)

<KerasTensor shape=(None, 1), dtype=float32, sparse=False, ragged=False, name=keras_tensor_15>

In [13]:
siamese_model = Model(
    inputs=[input_a, input_b],
    outputs=prediction
)

siamese_model.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 1)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ input_layer_2       │ (None, 224, 224,  │          0 │ -                 │
│ (InputLayer)        │ 1)                │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ functional          │ (None, 128)       │ 23,906,816 │ input_layer_1[0]… │
│ (Functional)        │                   │            │ input_layer_2[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ lambda (Lambda)     │ (None, 128)       │          0 │ functional[0][0], │
│                     │                   │            │ functional[1][0]  │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_1 (Dense)     │ (None, 1)         │        129 │ lambda[0][0]      │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 23,906,945 (91.20 MB)

 Trainable params: 23,906,945 (91.20 MB)

 Non-trainable params: 0 (0.00 B)

In [14]:
siamese_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

In [15]:
history = siamese_model.fit(
    [X1_train, X2_train],
    y_train,
    validation_data=([X1_test, X2_test], y_test),
    epochs=5,
    batch_size=32
)

Epoch 1/5
65/65 ━━━━━━━━━━━━━━━━━━━━ 240s 4s/step - accuracy: 0.6992 - loss: 0.4375 - val_accuracy: 0.7602 - val_loss: 0.3893
Epoch 2/5
65/65 ━━━━━━━━━━━━━━━━━━━━ 250s 3s/step - accuracy: 0.9275 - loss: 0.1883 - val_accuracy: 0.8743 - val_loss: 0.2560
Epoch 3/5
65/65 ━━━━━━━━━━━━━━━━━━━━ 266s 4s/step - accuracy: 0.9879 - loss: 0.0734 - val_accuracy: 0.9207 - val_loss: 0.1799
Epoch 4/5
65/65 ━━━━━━━━━━━━━━━━━━━━ 260s 4s/step - accuracy: 0.9937 - loss: 0.0356 - val_accuracy: 0.9226 - val_loss: 0.1954
Epoch 5/5
65/65 ━━━━━━━━━━━━━━━━━━━━ 225s 3s/step - accuracy: 0.9947 - loss: 0.0232 - val_accuracy: 0.8298 - val_loss: 0.4779

In [16]:
loss, accuracy = siamese_model.evaluate(
    [X1_test, X2_test],
    y_test
)

print("Test Loss:", loss)
print("Test Accuracy:", accuracy)

17/17 ━━━━━━━━━━━━━━━━━━━━ 13s 788ms/step - accuracy: 0.8298 - loss: 0.4779
Test Loss: 0.47792673110961914
Test Accuracy: 0.8297872543334961

In [17]:
siamese_model.save(
    "/content/drive/MyDrive/Signature_Project/siamese_signature_model.keras"
)

print("Model Saved Successfully")

Model Saved Successfully

In [24]:
import os

org_path = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"

print(os.listdir(org_path)[:10])

['original_26_22.png', 'original_19_16.png', 'original_1_1.png', 'original_25_5.png', 'original_2_4.png', 'original_1_2.png', 'original_18_21.png', 'original_26_10.png', 'original_21_14.png', 'original_19_9.png']

In [33]:
img1_name = "original_1_1.png"
img2_name = "original_1_2.png"

print(img1_name)
print(img2_name)

original_1_1.png
original_1_2.png

In [34]:
import cv2
import numpy as np

org_path = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"

img1 = cv2.imread(os.path.join(org_path, img1_name), cv2.IMREAD_GRAYSCALE)
img2 = cv2.imread(os.path.join(org_path, img2_name), cv2.IMREAD_GRAYSCALE)

img1 = cv2.resize(img1, (224, 224))
img2 = cv2.resize(img2, (224, 224))

img1 = img1 / 255.0
img2 = img2 / 255.0

img1 = img1.reshape(1, 224, 224, 1)
img2 = img2.reshape(1, 224, 224, 1)

print(img1.shape)
print(img2.shape)

(1, 224, 224, 1)
(1, 224, 224, 1)

In [35]:
prediction = siamese_model.predict([img1, img2])

print("Raw Prediction:", prediction)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Raw Prediction: [[0.9601993]]

In [36]:
score = prediction[0][0]

if score > 0.5:
    print("✅ Genuine Signature")
    print(f"Confidence: {score*100:.2f}%")
else:
    print("❌ Forgery")
    print(f"Confidence: {(1-score)*100:.2f}%")

✅ Genuine Signature
Confidence: 96.02%

In [37]:
import os

print(os.listdir("/content/drive/MyDrive/Signature_Project/cedar/signatures"))

['Readme.txt', 'full_forg', 'full_org']

In [38]:
import os
import cv2
import numpy as np

# Images to compare
img1_name = "original_1_1.png"
img2_name = "forgeries_1_1.png"

# Paths
org_path = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"
forg_path = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg"

# Read images
img1 = cv2.imread(
    os.path.join(org_path, img1_name),
    cv2.IMREAD_GRAYSCALE
)

img2 = cv2.imread(
    os.path.join(forg_path, img2_name),
    cv2.IMREAD_GRAYSCALE
)

# Resize
img1 = cv2.resize(img1, (224, 224))
img2 = cv2.resize(img2, (224, 224))

# Normalize
img1 = img1 / 255.0
img2 = img2 / 255.0

# Add batch dimension
img1 = img1.reshape(1, 224, 224, 1)
img2 = img2.reshape(1, 224, 224, 1)

# Predict
prediction = siamese_model.predict([img1, img2])

score = prediction[0][0]

print("Raw Score:", score)

if score > 0.5:
    print("✅ Genuine Signature")
    print(f"Confidence: {score*100:.2f}%")
else:
    print("❌ Forgery")
    print(f"Confidence: {(1-score)*100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step
Raw Score: 4.8779875e-10
❌ Forgery
Confidence: 100.00%

In [39]:
import os
import cv2
import numpy as np

ORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_org"
FORG_PATH = "/content/drive/MyDrive/Signature_Project/cedar/signatures/full_forg"

def predict_signature(img1_name, img2_name):

    # Decide folder for image 1
    if img1_name.startswith("original"):
        img1_path = os.path.join(ORG_PATH, img1_name)
    else:
        img1_path = os.path.join(FORG_PATH, img1_name)

    # Decide folder for image 2
    if img2_name.startswith("original"):
        img2_path = os.path.join(ORG_PATH, img2_name)
    else:
        img2_path = os.path.join(FORG_PATH, img2_name)

    # Read images
    img1 = cv2.imread(img1_path, cv2.IMREAD_GRAYSCALE)
    img2 = cv2.imread(img2_path, cv2.IMREAD_GRAYSCALE)

    # Resize
    img1 = cv2.resize(img1, (224, 224))
    img2 = cv2.resize(img2, (224, 224))

    # Normalize
    img1 = img1 / 255.0
    img2 = img2 / 255.0

    # Reshape
    img1 = img1.reshape(1, 224, 224, 1)
    img2 = img2.reshape(1, 224, 224, 1)

    # Predict
    prediction = siamese_model.predict([img1, img2], verbose=0)

    score = prediction[0][0]

    print("\nPrediction Score:", score)

    if score > 0.5:
        print("✅ Genuine Signature")
        print(f"Confidence: {score*100:.2f}%")
    else:
        print("❌ Forgery")
        print(f"Confidence: {(1-score)*100:.2f}%")

In [40]:
predict_signature(
    "original_1_1.png",
    "original_1_2.png"
)

Prediction Score: 0.9601993
✅ Genuine Signature
Confidence: 96.02%